@echo off
echo Running Dedupe Clean...
.venv\Scripts\python.exe scripts\dedupe_clean.py data\raw\pages_full_20260304_1333.jsonl data\clean\pages_clean_full_dedup.jsonl
echo Running Post Clean...
.venv\Scripts\python.exe scripts\post_clean.py data\clean\pages_clean_full_dedup.jsonl data\clean\pages_for_index.jsonl
echo Running Filter For Index...
.venv\Scripts\python.exe scripts\filter_for_index.py data\clean\pages_for_index.jsonl data\clean\pages_for_index_filtered.jsonl
echo Running Make Chunks...
.venv\Scripts\python.exe scripts\make_chunks.py data\clean\pages_for_index_filtered.jsonl data\chunks\chunks.jsonl
echo Running Build Chroma...
.venv\Scripts\python.exe scripts\build_chroma.py data\chunks\chunks.jsonl data\chroma_db
echo Pipeline Finished!
